/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Case {
  'customerName' : string,
  'status' : string,
  'customerNumber' : string,
  'mobileNumber' : string,
  'productType' : string,
  'outstandingBalance' : number,
  'caseId' : string,
  'omniflowNumber' : string,
  'assignedAgency' : string,
  'caseDescription' : string,
  'contractId' : string,
}
export type DeliveryMethod = { 'courier' : null } |
  { 'email' : null } |
  { 'physical' : null };
export interface EnforcementRecord {
  'status' : string,
  'enforcementType' : string,
  'responsibleLegalParty' : string,
  'initiationDate' : Time,
  'amountRecovered' : number,
}
export type Judgement = { 'propertyLien' : null } |
  { 'assetRepossession' : null } |
  { 'none' : null } |
  { 'wageGarnishment' : null } |
  { 'auction' : null } |
  { 'writOfSeizureSale' : null };
export interface LitigationRecord {
  'hearingDate' : [] | [Time],
  'judgement' : Judgement,
  'caseStatus' : LitigationStatus,
  'courtSummonsDate' : [] | [Time],
  'courtCaseNumber' : string,
  'filingDate' : Time,
  'courtName' : string,
}
export type LitigationStatus = { 'filed' : null } |
  { 'judgementIssued' : null } |
  { 'awaitingHearing' : null } |
  { 'inTrial' : null };
export interface NoticeRecord {
  'noticeType' : NoticeType,
  'noticeSentDate' : Time,
  'deliveryStatus' : string,
  'deliveryMethod' : DeliveryMethod,
  'noticeExpiryDate' : Time,
  'noticeStatus' : NoticeStatus,
  'noticeId' : string,
  'caseId' : string,
}
export type NoticeStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'complied' : null };
export type NoticeType = { 'firstDemand' : null } |
  { 'statutory' : null } |
  { 'finalDemand' : null };
export type Time = bigint;
export interface _SERVICE {
  'addCase' : ActorMethod<[Case], undefined>,
  'getCase' : ActorMethod<[string], Case>,
  'getCases' : ActorMethod<[], Array<Case>>,
  'getEnforcement' : ActorMethod<[string], EnforcementRecord>,
  'getLitigation' : ActorMethod<[string], LitigationRecord>,
  'getNotices' : ActorMethod<[string], Array<NoticeRecord>>,
  'updateCase' : ActorMethod<[string, Case], undefined>,
  'updateEnforcement' : ActorMethod<[string, EnforcementRecord], undefined>,
  'updateLitigation' : ActorMethod<[string, LitigationRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];