/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Case = IDL.Record({
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'customerNumber' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'productType' : IDL.Text,
  'outstandingBalance' : IDL.Float64,
  'caseId' : IDL.Text,
  'omniflowNumber' : IDL.Text,
  'assignedAgency' : IDL.Text,
  'caseDescription' : IDL.Text,
  'contractId' : IDL.Text,
});
export const Time = IDL.Int;
export const EnforcementRecord = IDL.Record({
  'status' : IDL.Text,
  'enforcementType' : IDL.Text,
  'responsibleLegalParty' : IDL.Text,
  'initiationDate' : Time,
  'amountRecovered' : IDL.Float64,
});
export const Judgement = IDL.Variant({
  'propertyLien' : IDL.Null,
  'assetRepossession' : IDL.Null,
  'none' : IDL.Null,
  'wageGarnishment' : IDL.Null,
  'auction' : IDL.Null,
  'writOfSeizureSale' : IDL.Null,
});
export const LitigationStatus = IDL.Variant({
  'filed' : IDL.Null,
  'judgementIssued' : IDL.Null,
  'awaitingHearing' : IDL.Null,
  'inTrial' : IDL.Null,
});
export const LitigationRecord = IDL.Record({
  'hearingDate' : IDL.Opt(Time),
  'judgement' : Judgement,
  'caseStatus' : LitigationStatus,
  'courtSummonsDate' : IDL.Opt(Time),
  'courtCaseNumber' : IDL.Text,
  'filingDate' : Time,
  'courtName' : IDL.Text,
});
export const NoticeType = IDL.Variant({
  'firstDemand' : IDL.Null,
  'statutory' : IDL.Null,
  'finalDemand' : IDL.Null,
});
export const DeliveryMethod = IDL.Variant({
  'courier' : IDL.Null,
  'email' : IDL.Null,
  'physical' : IDL.Null,
});
export const NoticeStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'complied' : IDL.Null,
});
export const NoticeRecord = IDL.Record({
  'noticeType' : NoticeType,
  'noticeSentDate' : Time,
  'deliveryStatus' : IDL.Text,
  'deliveryMethod' : DeliveryMethod,
  'noticeExpiryDate' : Time,
  'noticeStatus' : NoticeStatus,
  'noticeId' : IDL.Text,
  'caseId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCase' : IDL.Func([Case], [], []),
  'getCase' : IDL.Func([IDL.Text], [Case], ['query']),
  'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getEnforcement' : IDL.Func([IDL.Text], [EnforcementRecord], ['query']),
  'getLitigation' : IDL.Func([IDL.Text], [LitigationRecord], ['query']),
  'getNotices' : IDL.Func([IDL.Text], [IDL.Vec(NoticeRecord)], ['query']),
  'updateCase' : IDL.Func([IDL.Text, Case], [], []),
  'updateEnforcement' : IDL.Func([IDL.Text, EnforcementRecord], [], []),
  'updateLitigation' : IDL.Func([IDL.Text, LitigationRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Case = IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'customerNumber' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'productType' : IDL.Text,
    'outstandingBalance' : IDL.Float64,
    'caseId' : IDL.Text,
    'omniflowNumber' : IDL.Text,
    'assignedAgency' : IDL.Text,
    'caseDescription' : IDL.Text,
    'contractId' : IDL.Text,
  });
  const Time = IDL.Int;
  const EnforcementRecord = IDL.Record({
    'status' : IDL.Text,
    'enforcementType' : IDL.Text,
    'responsibleLegalParty' : IDL.Text,
    'initiationDate' : Time,
    'amountRecovered' : IDL.Float64,
  });
  const Judgement = IDL.Variant({
    'propertyLien' : IDL.Null,
    'assetRepossession' : IDL.Null,
    'none' : IDL.Null,
    'wageGarnishment' : IDL.Null,
    'auction' : IDL.Null,
    'writOfSeizureSale' : IDL.Null,
  });
  const LitigationStatus = IDL.Variant({
    'filed' : IDL.Null,
    'judgementIssued' : IDL.Null,
    'awaitingHearing' : IDL.Null,
    'inTrial' : IDL.Null,
  });
  const LitigationRecord = IDL.Record({
    'hearingDate' : IDL.Opt(Time),
    'judgement' : Judgement,
    'caseStatus' : LitigationStatus,
    'courtSummonsDate' : IDL.Opt(Time),
    'courtCaseNumber' : IDL.Text,
    'filingDate' : Time,
    'courtName' : IDL.Text,
  });
  const NoticeType = IDL.Variant({
    'firstDemand' : IDL.Null,
    'statutory' : IDL.Null,
    'finalDemand' : IDL.Null,
  });
  const DeliveryMethod = IDL.Variant({
    'courier' : IDL.Null,
    'email' : IDL.Null,
    'physical' : IDL.Null,
  });
  const NoticeStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'complied' : IDL.Null,
  });
  const NoticeRecord = IDL.Record({
    'noticeType' : NoticeType,
    'noticeSentDate' : Time,
    'deliveryStatus' : IDL.Text,
    'deliveryMethod' : DeliveryMethod,
    'noticeExpiryDate' : Time,
    'noticeStatus' : NoticeStatus,
    'noticeId' : IDL.Text,
    'caseId' : IDL.Text,
  });
  
  return IDL.Service({
    'addCase' : IDL.Func([Case], [], []),
    'getCase' : IDL.Func([IDL.Text], [Case], ['query']),
    'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getEnforcement' : IDL.Func([IDL.Text], [EnforcementRecord], ['query']),
    'getLitigation' : IDL.Func([IDL.Text], [LitigationRecord], ['query']),
    'getNotices' : IDL.Func([IDL.Text], [IDL.Vec(NoticeRecord)], ['query']),
    'updateCase' : IDL.Func([IDL.Text, Case], [], []),
    'updateEnforcement' : IDL.Func([IDL.Text, EnforcementRecord], [], []),
    'updateLitigation' : IDL.Func([IDL.Text, LitigationRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };