/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LitigationRecord {
    hearingDate?: Time;
    judgement: Judgement;
    caseStatus: LitigationStatus;
    courtSummonsDate?: Time;
    courtCaseNumber: string;
    filingDate: Time;
    courtName: string;
}
export type Time = bigint;
export interface NoticeRecord {
    noticeType: NoticeType;
    noticeSentDate: Time;
    deliveryStatus: string;
    deliveryMethod: DeliveryMethod;
    noticeExpiryDate: Time;
    noticeStatus: NoticeStatus;
    noticeId: string;
    caseId: string;
}
export interface EnforcementRecord {
    status: string;
    enforcementType: string;
    responsibleLegalParty: string;
    initiationDate: Time;
    amountRecovered: number;
}
export interface Case {
    customerName: string;
    status: string;
    customerNumber: string;
    mobileNumber: string;
    productType: string;
    outstandingBalance: number;
    caseId: string;
    omniflowNumber: string;
    assignedAgency: string;
    caseDescription: string;
    contractId: string;
}
export enum DeliveryMethod {
    courier = "courier",
    email = "email",
    physical = "physical"
}
export enum Judgement {
    propertyLien = "propertyLien",
    assetRepossession = "assetRepossession",
    none = "none",
    wageGarnishment = "wageGarnishment",
    auction = "auction",
    writOfSeizureSale = "writOfSeizureSale"
}
export enum LitigationStatus {
    filed = "filed",
    judgementIssued = "judgementIssued",
    awaitingHearing = "awaitingHearing",
    inTrial = "inTrial"
}
export enum NoticeStatus {
    active = "active",
    expired = "expired",
    complied = "complied"
}
export enum NoticeType {
    firstDemand = "firstDemand",
    statutory = "statutory",
    finalDemand = "finalDemand"
}
export interface backendInterface {
    addCase(newCase: Case): Promise<void>;
    getCase(caseId: string): Promise<Case>;
    getCases(): Promise<Array<Case>>;
    getEnforcement(caseId: string): Promise<EnforcementRecord>;
    getLitigation(caseId: string): Promise<LitigationRecord>;
    getNotices(caseId: string): Promise<Array<NoticeRecord>>;
    updateCase(caseId: string, updatedCase: Case): Promise<void>;
    updateEnforcement(caseId: string, record: EnforcementRecord): Promise<void>;
    updateLitigation(caseId: string, record: LitigationRecord): Promise<void>;
}
import type { DeliveryMethod as _DeliveryMethod, Judgement as _Judgement, LitigationRecord as _LitigationRecord, LitigationStatus as _LitigationStatus, NoticeRecord as _NoticeRecord, NoticeStatus as _NoticeStatus, NoticeType as _NoticeType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCase(arg0: Case): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCase(arg0);
            return result;
        }
    }
    async getCase(arg0: string): Promise<Case> {
        if (this.processError) {
            try {
                const result = await this.actor.getCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCase(arg0);
            return result;
        }
    }
    async getCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCases();
            return result;
        }
    }
    async getEnforcement(arg0: string): Promise<EnforcementRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnforcement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnforcement(arg0);
            return result;
        }
    }
    async getLitigation(arg0: string): Promise<LitigationRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getLitigation(arg0);
                return from_candid_LitigationRecord_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLitigation(arg0);
            return from_candid_LitigationRecord_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotices(arg0: string): Promise<Array<NoticeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotices(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotices(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCase(arg0: string, arg1: Case): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCase(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCase(arg0, arg1);
            return result;
        }
    }
    async updateEnforcement(arg0: string, arg1: EnforcementRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEnforcement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEnforcement(arg0, arg1);
            return result;
        }
    }
    async updateLitigation(arg0: string, arg1: LitigationRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLitigation(arg0, to_candid_LitigationRecord_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLitigation(arg0, to_candid_LitigationRecord_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DeliveryMethod_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryMethod): DeliveryMethod {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Judgement_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Judgement): Judgement {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_LitigationRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LitigationRecord): LitigationRecord {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_LitigationStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LitigationStatus): LitigationStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_NoticeRecord_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeRecord): NoticeRecord {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_NoticeStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeStatus): NoticeStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NoticeType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeType): NoticeType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    noticeType: _NoticeType;
    noticeSentDate: _Time;
    deliveryStatus: string;
    deliveryMethod: _DeliveryMethod;
    noticeExpiryDate: _Time;
    noticeStatus: _NoticeStatus;
    noticeId: string;
    caseId: string;
}): {
    noticeType: NoticeType;
    noticeSentDate: Time;
    deliveryStatus: string;
    deliveryMethod: DeliveryMethod;
    noticeExpiryDate: Time;
    noticeStatus: NoticeStatus;
    noticeId: string;
    caseId: string;
} {
    return {
        noticeType: from_candid_NoticeType_n11(_uploadFile, _downloadFile, value.noticeType),
        noticeSentDate: value.noticeSentDate,
        deliveryStatus: value.deliveryStatus,
        deliveryMethod: from_candid_DeliveryMethod_n13(_uploadFile, _downloadFile, value.deliveryMethod),
        noticeExpiryDate: value.noticeExpiryDate,
        noticeStatus: from_candid_NoticeStatus_n15(_uploadFile, _downloadFile, value.noticeStatus),
        noticeId: value.noticeId,
        caseId: value.caseId
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hearingDate: [] | [_Time];
    judgement: _Judgement;
    caseStatus: _LitigationStatus;
    courtSummonsDate: [] | [_Time];
    courtCaseNumber: string;
    filingDate: _Time;
    courtName: string;
}): {
    hearingDate?: Time;
    judgement: Judgement;
    caseStatus: LitigationStatus;
    courtSummonsDate?: Time;
    courtCaseNumber: string;
    filingDate: Time;
    courtName: string;
} {
    return {
        hearingDate: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.hearingDate)),
        judgement: from_candid_Judgement_n4(_uploadFile, _downloadFile, value.judgement),
        caseStatus: from_candid_LitigationStatus_n6(_uploadFile, _downloadFile, value.caseStatus),
        courtSummonsDate: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.courtSummonsDate)),
        courtCaseNumber: value.courtCaseNumber,
        filingDate: value.filingDate,
        courtName: value.courtName
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    firstDemand: null;
} | {
    statutory: null;
} | {
    finalDemand: null;
}): NoticeType {
    return "firstDemand" in value ? NoticeType.firstDemand : "statutory" in value ? NoticeType.statutory : "finalDemand" in value ? NoticeType.finalDemand : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    courier: null;
} | {
    email: null;
} | {
    physical: null;
}): DeliveryMethod {
    return "courier" in value ? DeliveryMethod.courier : "email" in value ? DeliveryMethod.email : "physical" in value ? DeliveryMethod.physical : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    complied: null;
}): NoticeStatus {
    return "active" in value ? NoticeStatus.active : "expired" in value ? NoticeStatus.expired : "complied" in value ? NoticeStatus.complied : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyLien: null;
} | {
    assetRepossession: null;
} | {
    none: null;
} | {
    wageGarnishment: null;
} | {
    auction: null;
} | {
    writOfSeizureSale: null;
}): Judgement {
    return "propertyLien" in value ? Judgement.propertyLien : "assetRepossession" in value ? Judgement.assetRepossession : "none" in value ? Judgement.none : "wageGarnishment" in value ? Judgement.wageGarnishment : "auction" in value ? Judgement.auction : "writOfSeizureSale" in value ? Judgement.writOfSeizureSale : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filed: null;
} | {
    judgementIssued: null;
} | {
    awaitingHearing: null;
} | {
    inTrial: null;
}): LitigationStatus {
    return "filed" in value ? LitigationStatus.filed : "judgementIssued" in value ? LitigationStatus.judgementIssued : "awaitingHearing" in value ? LitigationStatus.awaitingHearing : "inTrial" in value ? LitigationStatus.inTrial : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NoticeRecord>): Array<NoticeRecord> {
    return value.map((x)=>from_candid_NoticeRecord_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Judgement_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Judgement): _Judgement {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_LitigationRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LitigationRecord): _LitigationRecord {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_LitigationStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LitigationStatus): _LitigationStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hearingDate?: Time;
    judgement: Judgement;
    caseStatus: LitigationStatus;
    courtSummonsDate?: Time;
    courtCaseNumber: string;
    filingDate: Time;
    courtName: string;
}): {
    hearingDate: [] | [_Time];
    judgement: _Judgement;
    caseStatus: _LitigationStatus;
    courtSummonsDate: [] | [_Time];
    courtCaseNumber: string;
    filingDate: _Time;
    courtName: string;
} {
    return {
        hearingDate: value.hearingDate ? candid_some(value.hearingDate) : candid_none(),
        judgement: to_candid_Judgement_n19(_uploadFile, _downloadFile, value.judgement),
        caseStatus: to_candid_LitigationStatus_n21(_uploadFile, _downloadFile, value.caseStatus),
        courtSummonsDate: value.courtSummonsDate ? candid_some(value.courtSummonsDate) : candid_none(),
        courtCaseNumber: value.courtCaseNumber,
        filingDate: value.filingDate,
        courtName: value.courtName
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Judgement): {
    propertyLien: null;
} | {
    assetRepossession: null;
} | {
    none: null;
} | {
    wageGarnishment: null;
} | {
    auction: null;
} | {
    writOfSeizureSale: null;
} {
    return value == Judgement.propertyLien ? {
        propertyLien: null
    } : value == Judgement.assetRepossession ? {
        assetRepossession: null
    } : value == Judgement.none ? {
        none: null
    } : value == Judgement.wageGarnishment ? {
        wageGarnishment: null
    } : value == Judgement.auction ? {
        auction: null
    } : value == Judgement.writOfSeizureSale ? {
        writOfSeizureSale: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LitigationStatus): {
    filed: null;
} | {
    judgementIssued: null;
} | {
    awaitingHearing: null;
} | {
    inTrial: null;
} {
    return value == LitigationStatus.filed ? {
        filed: null
    } : value == LitigationStatus.judgementIssued ? {
        judgementIssued: null
    } : value == LitigationStatus.awaitingHearing ? {
        awaitingHearing: null
    } : value == LitigationStatus.inTrial ? {
        inTrial: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
